spring.application.name=skylink-media-service
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/skylink_media_service
# 
# spring.datasource.username=mhcybroot
# spring.datasource.password=MhR@2025
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=uploads

# Thymeleaf settings
spring.thymeleaf.cache=false