spring.application.name=skylink-media-service
spring.datasource.url=jdbc:postgresql://localhost:5432/skylink_media_service
spring.datasource.username=mhcybroot
spring.datasource.password=MhR@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect